### ISSUE TITLE
discussion: how should hashes get written?

### ISSUE THREAD

**Issue by dankelley** [dankelley/nb#11]
Right now, I'm showing 4 chars. An alternative is to trim the number to the minimum that distinguishes the notes, which would make it easier for users to "drill down" to individual notes.

I am inclined to trim, but a disadvantage of that might crop up if I permit notes to refer to each other. The problem is that with a small number of notes a single char might be okay, but referencing that will fail as more notes are added and collisions come into play. Well, I guess this is not terribly serious because any more than a handful of notes will give 2 chars as the min, and then you have 40^2 possibilities, which is large.

Another reason I am not keen on trimming is that I find the 4 chars quite evocative ... a single char doesn't "look like" a hash to me.

PS. Maybe the has should have a # in front ... twitter people might like that.

**Comment by richardsc** [comment]
I actually don't mind the 4 char hashes. One thing I noticed is that you don't actually have to type all 4 chars to properly reference the note. E.g.
```
$ nb c
c1d9 - do tidal model on decimated series [ fjord, paper, ice ]
c4b2 - bash prompt from title of README if present [ bash, shell, prompt, readme, idea ]
c913 - polar dispatches bio [ blog,  bio,  polar dispatches ]

HINT: to delete e.g. note wth hash 'ab...', type "nb -d ab"
$ nb c4
c4b2 - bash prompt from title of README if present [ bash, shell, prompt, readme, idea ]
  2013-03-04 19:16:40 
  It would be handy to have a thing in the bash prompt that instead of
  just telling me there is a README file present, displays the first
  line (or perhaps just the line after a #) in the prompt, so that I
  know quicker what directory I'm working in.
```

**Comment by dankelley** [comment]
Yes, abbrevs work. I touch on that a bit in the docs. I'll also update the README when the interface stabilizes a bit more, to include examples. The advantage of a readme is that it's easier to distinguish code with fonts, etc. I miss the nice docs that can be put into R packages.

**Comment by dankelley** [comment]
I feel that this can be closed. There can always be a new issue called (say) ``hashes should be written as [format]``.
