### ISSUE TITLE
'nb' should be packaged

### ISSUE THREAD

**Issue by dankelley** [dankelley/nb#19]
It looks pretty easy to install on the archive; see e.g. hints at http://www.scotttorborg.com/python-packaging/minimal.html 

NOTE: the name ``nb`` is already taken, though (and for a similar purpose!  See the list of python package names at https://pypi.python.org/pypi?%3Aaction=index

**Comment by dankelley** [comment]
Hm, the name ``notabene`` is taken also. A lot of note-taking packages seem to be in that list.

**Comment by dankelley** [comment]
I see that ``nota`` is not taken. And that's the verb of "nota bene", so I think it may be a good name.

**Comment by richardsc** [comment]
Hm, that's a bummer. I like the name `nota`.

I will probably do as you do, and alias whatever it gets called to `nb` anyway.

**Comment by dankelley** [comment]
I put in a placeholder on pypi for ``nota`` https://pypi.python.org/pypi/nota/0.4

Man, the threshold for getting a "package" accepted is a bit on the low side. (Fill in a name and version number, and you're in.)

I will probably rename the present repo as ``nota``. I guess I could also start a new repo. Not sure which is best; will decide on Thursday. In any case, the database files will transfer over.

**Comment by dankelley** [comment]
Done. The new GH page is https://github.com/dankelley/nota and also the package is now on pypi.python.org
