### ISSUE TITLE
"nb -k" is broken

### ISSUE THREAD

**Issue by richardsc** [dankelley/nb#9]
Trying commit a8fb7a1ae64a, (spawned from issue #8). I like the output, however it seems like the keyword searching is broken.

```
$ nb
c1d9 - (4) do tidal model on decimated series [ fjord, paper, ice ]
8860 - (12) plotting filled contours in a map projection [ R, maps, contours ]
9feb - (13) code in densityScatter function to library [ R,  plotting ]
c4b2 - (18) bash prompt from title of README if present [ bash, shell, prompt, readme, idea ]
7e50 - (22) Thoughts about long period ocean waves in seismometers; filtering artifact? [ filtering,  waves,  ice,  tsunami,  greenland,  fjord ]
6def - (32) TODO [ todo ]
079b - (38) getting inkscape working with tex text [ inkscape, textext, osx ]
6523 - (39) plotting g_rect rectifications in R [ g_rect, R, plotting, maps ]
0a58 - (57) Skype meeting with Ken [ fjord, glacier, paper, plume, greenland ]
a688 - (58) Group blog Meeting notes [ whoi, blog, polar dispatches, wordpress ]
c913 - (68) polar dispatches bio [ blog,  bio,  polar dispatches ]
1508 - (71) disable Rnw support in polymode [ polymode ]
HINT: to read notes from a JSON file, type "nb -a -m json < notes.json"
```

Then, search by keyword gives the full list:
```
$ nb -k R
c1d9 - (4) do tidal model on decimated series [ fjord, paper, ice ]
8860 - (12) plotting filled contours in a map projection [ R, maps, contours ]
9feb - (13) code in densityScatter function to library [ R,  plotting ]
c4b2 - (18) bash prompt from title of README if present [ bash, shell, prompt, readme, idea ]
7e50 - (22) Thoughts about long period ocean waves in seismometers; filtering artifact? [ filtering,  waves,  ice,  tsunami,  greenland,  fjord ]
6def - (32) TODO [ todo ]
079b - (38) getting inkscape working with tex text [ inkscape, textext, osx ]
6523 - (39) plotting g_rect rectifications in R [ g_rect, R, plotting, maps ]
0a58 - (57) Skype meeting with Ken [ fjord, glacier, paper, plume, greenland ]
a688 - (58) Group blog Meeting notes [ whoi, blog, polar dispatches, wordpress ]
c913 - (68) polar dispatches bio [ blog,  bio,  polar dispatches ]
1508 - (71) disable Rnw support in polymode [ polymode ]
HINT: to see notes with keyword 'foo', type "nb -k foo"
```

**Comment by dankelley** [comment]
Yup, it's broken. I didn't bother making an issue cuz I didn't think anyone would be using it!  The move to hash codes has required a lot of things to change and I'm fixing them one by one. I think I have ``-a``, ``-e`` and ``-d`` working at this stage ... but this is *not safe* to use (especially delete).

Right now it displays 4 hash chars because that was 4 lines less coding and I had other things to fix.

PS. the parenthetic SQL id number is temporary. In the latest ``develop`` version, you can turn that on and off a ``showID = True`` line in ``~/.nbrc`` ... but that may change since I'm playing with things quite actively for a day or two.

**Comment by richardsc** [comment]
Ha, sorry. I'm just too keen! Feel free to close whenever.

**Comment by dankelley** [comment]
I think it's fixed but maybe you can check.

NOTE: it's important to back up your database once in a while, to protect against errors while I'm messing around. You probably don't notice it, but the first thing ``nb`` does when it launches is to check the version number of the database, and if it's old, it updates things by adding columns etc. For example, we got hashes in the past few days, and they get inserted into old-style databases with code starting at line 72 of ``nbclass.py``.

**Comment by dankelley** [comment]
Fixed.
